Test: retrait du scan ZAP

diff --git a/.github/workflows/ci-zap.yml b/.github/workflows/ci-zap.yml
--- a/.github/workflows/ci-zap.yml
+++ b/.github/workflows/ci-zap.yml
@@ -104,16 +104,16 @@ jobs:
           echo "===== LOGS API ====="
           tail -n 200 /tmp/api.log || true
             
-      - name: Scan OWASP ZAP
-        uses: zaproxy/action-api-scan@v0.10.0
-        with:
-          target: "http://127.0.0.1:8000/api/docs.jsonopenapi"
-          format: openapi
-          rules_file_name: ".zap/rules.tsv"
-          allow_issue_writing: false
-          fail_action: true
-          cmd_options: "-I"
+      # - name: Scan OWASP ZAP
+      #   uses: zaproxy/action-api-scan@v0.10.0
+      #   with:
+      #     target: "http://127.0.0.1:8000/api/docs.jsonopenapi"
+      #     format: openapi
+      #     rules_file_name: ".zap/rules.tsv"
+      #     allow_issue_writing: false
+      #     fail_action: true
+      #     cmd_options: "-I"
 
-      - name: Affichage des logs en cas d'échec
-        if: failure()
-        run: tail -n 200 /tmp/api.log || true
+      # - name: Affichage des logs en cas d'échec
+      #   if: failure()
+      #   run: tail -n 200 /tmp/api.log || true
