Test: log de routes ZAP

diff --git a/.github/workflows/ci-zap.yml b/.github/workflows/ci-zap.yml
--- a/.github/workflows/ci-zap.yml
+++ b/.github/workflows/ci-zap.yml
@@ -80,16 +80,29 @@ jobs:
           cat /tmp/api.log
           exit 1
       
+      # - name: Vérification des routes avant ZAP
+      #   run: |
+      #     set -euo pipefail
+
+      #     curl --fail-with-body --silent --show-error \
+      #       "http://127.0.0.1:8000/api/categories?page=1"
+
+      #     curl --fail-with-body --silent --show-error \
+      #       "http://127.0.0.1:8000/api/ressources?page=1"
       - name: Vérification des routes avant ZAP
         run: |
-          set -euo pipefail
+          echo "===== /api/categories ====="
+          curl --silent --show-error --include \
+            "http://127.0.0.1:8000/api/categories?page=1" || true
 
-          curl --fail-with-body --silent --show-error \
-            "http://127.0.0.1:8000/api/categories?page=1"
+          echo ""
+          echo "===== /api/ressources ====="
+          curl --silent --show-error --include \
+            "http://127.0.0.1:8000/api/ressources?page=1" || true
 
-          curl --fail-with-body --silent --show-error \
-            "http://127.0.0.1:8000/api/ressources?page=1"
-
+          echo ""
+          echo "===== LOGS API ====="
+          tail -n 200 /tmp/api.log || true
             
       - name: Scan OWASP ZAP
         uses: zaproxy/action-api-scan@v0.10.0
